services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./broker-config:/mosquitto/config:rw
      - ./broker-data:/mosquitto/data:rw
      - ./broker-log:/mosquitto/log:rw
    networks:
      - home-iot-network

  # InfluxDB
  influxdb:
    image: influxdb:2-alpine
    container_name: influxdb
    ports:
      - "8090:8086" # InfluxDB API port
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - ./influxdb:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
    networks:
      - home-iot-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3005:3000'
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana-config/custom.ini:/etc/grafana/custom.ini:ro
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    networks:
      - home-iot-network

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:
  influxdb:
  grafana:

networks:
  home-iot-network:
    name: home-iot-network
