{
 "title": "Smart Home Sensors (PI1)",
 "tags": [
  "smarthome",
  "iot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Motion (DPIR1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"motion\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.code == \"DPIR1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "LED Control (DL)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"led\" and r._field == \"value\" and r.code == \"DL\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group()"
    }
   ]
  },
  {
   "title": "Membrane Attempts (DMS)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"membrane_attempt\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.code == \"DMS\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Membrane Key Presses (DMS)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"membrane_key\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.code == \"DMS\")\n  |> aggregateWindow(every: 100ms, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Door Button (DS1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"button\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"code\"] == \"DS1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Buzzer Activation (DB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r._measurement == \"buzzer\" and r.code == \"DB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"code\"], mode:\"by\")"
    }
   ]
  },
  {
   "title": "Door Distance (DUS1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lengthcm" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"ultrasonic\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.code == \"DUS1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  }
 ]
}